import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProgressiveBlur } from "@/components/progressive-blur";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        {/* 2. Add Top Blur */}
        <ProgressiveBlur 
          position="top" 
          height="100px" 
          blurAmount="4px" 
          backgroundColor="#09090b" 
        />

        {/* This is where your page content (Home, About, etc.) goes */}
        {children}

        {/* 3. Add Bottom Blur */}
        <ProgressiveBlur 
          position="bottom" 
          height="100px" 
          blurAmount="4px" 
          backgroundColor="#09090b" 
        />
      </body>
    </html>
  );
}
